-- MySQL Script generated by MySQL Workbench
-- Sun Aug 15 16:59:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema electronic_session
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema electronic_session
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `electronic_session` DEFAULT CHARACTER SET utf8 ;
USE `electronic_session` ;

-- -----------------------------------------------------
-- Table `electronic_session`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electronic_session`.`user` ;

CREATE TABLE IF NOT EXISTS `electronic_session`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `is_admin` TINYINT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electronic_session`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electronic_session`.`session` ;

CREATE TABLE IF NOT EXISTS `electronic_session`.`session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `id_user` INT NOT NULL,
  `archived` TINYINT NOT NULL,
  `conclusion` VARCHAR(1000) NOT NULL,
  `active_from` TIMESTAMP NOT NULL,
  `discussion_until` TIMESTAMP NOT NULL,
  `active_until` TIMESTAMP NOT NULL,
  `is_public` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_session_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_session_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `electronic_session`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electronic_session`.`agenda_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electronic_session`.`agenda_item` ;

CREATE TABLE IF NOT EXISTS `electronic_session`.`agenda_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_session` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `is_accepted` TINYINT NOT NULL,
  `is_vote_enabled` TINYINT NOT NULL,
  `is_discussion_enabled` TINYINT NOT NULL,
  `is_public_voting` TINYINT NOT NULL,
  `agenda_itemcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agenda_item_session_idx` (`id_session` ASC),
  CONSTRAINT `fk_agenda_item_session`
    FOREIGN KEY (`id_session`)
    REFERENCES `electronic_session`.`session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `electronic_session`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electronic_session`.`comment` ;

CREATE TABLE IF NOT EXISTS `electronic_session`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(250) NOT NULL,
  `id_user` INT NOT NULL,
  `id_agenda_item` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_user1_idx` (`id_user` ASC),
  INDEX `fk_comment_agenda_item1_idx` (`id_agenda_item` ASC),
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `electronic_session`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_agenda_item1`
    FOREIGN KEY (`id_agenda_item`)
    REFERENCES `electronic_session`.`agenda_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electronic_session`.`voting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electronic_session`.`voting` ;

CREATE TABLE IF NOT EXISTS `electronic_session`.`voting` (
  `idvoting` INT NOT NULL AUTO_INCREMENT,
  `for` TINYINT NOT NULL,
  `against` TINYINT NOT NULL,
  `restrained` TINYINT NOT NULL,
  `id_user` INT NOT NULL,
  `id_agenda_item` INT NOT NULL,
  `date_voted` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idvoting`),
  INDEX `fk_voting_user1_idx` (`id_user` ASC),
  INDEX `fk_voting_agenda_item1_idx` (`id_agenda_item` ASC),
  CONSTRAINT `fk_voting_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `electronic_session`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voting_agenda_item1`
    FOREIGN KEY (`id_agenda_item`)
    REFERENCES `electronic_session`.`agenda_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electronic_session`.`document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electronic_session`.`document` ;

CREATE TABLE IF NOT EXISTS `electronic_session`.`document` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `is_material` TINYINT NOT NULL,
  `id_user` INT NOT NULL,
  `id_agenda_item` INT NULL,
  `filename` VARCHAR(45) NOT NULL,
  `date_created` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_document_user1_idx` (`id_user` ASC),
  INDEX `fk_document_agenda_item1_idx` (`id_agenda_item` ASC),
  CONSTRAINT `fk_document_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `electronic_session`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_agenda_item1`
    FOREIGN KEY (`id_agenda_item`)
    REFERENCES `electronic_session`.`agenda_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electronic_session`.`remark`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electronic_session`.`remark` ;

CREATE TABLE IF NOT EXISTS `electronic_session`.`remark` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content_observation` VARCHAR(250) NOT NULL,
  `id_user` INT NOT NULL,
  `id_session` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_observation_user1_idx` (`id_user` ASC),
  INDEX `fk_observation_session1_idx` (`id_session` ASC),
  CONSTRAINT `fk_observation_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `electronic_session`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_observation_session1`
    FOREIGN KEY (`id_session`)
    REFERENCES `electronic_session`.`session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electronic_session`.`user_agenda_item_access`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electronic_session`.`user_agenda_item_access` ;

CREATE TABLE IF NOT EXISTS `electronic_session`.`user_agenda_item_access` (
  `id_user` INT NOT NULL,
  `id_agenda_item` INT NOT NULL,
  `enable_voting` TINYINT NOT NULL,
  `enable_discussion` TINYINT NOT NULL,
  PRIMARY KEY (`id_user`, `id_agenda_item`),
  INDEX `fk_user_has_agenda_item_agenda_item1_idx` (`id_agenda_item` ASC),
  INDEX `fk_user_has_agenda_item_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_user_has_agenda_item_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `electronic_session`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_agenda_item_agenda_item1`
    FOREIGN KEY (`id_agenda_item`)
    REFERENCES `electronic_session`.`agenda_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
